---
- name: Check if http2_chunk_size directive is set in location block
  when:
    - _location_block.http2_chunk_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        http2_chunk_size {{ _location_block.http2_chunk_size }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_chunk_size_directive

- name: Verify http2_chunk_size directive is set in location block
  when:
    - _location_block.http2_chunk_size is defined
  ansible.builtin.assert:
    that:
      - not _http2_chunk_size_directive.changed
    fail_msg: http2_chunk_size directive is not set in location block.
    success_msg: http2_chunk_size directive is set in location block.

- name: Check if http2_push directive is set in location block
  when:
    - _location_block.http2_push is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        http2_push {{ _location_block.http2_push }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_push_directive

- name: Verify http2_push directive is set in location block
  when:
    - _location_block.http2_push is defined
  ansible.builtin.assert:
    that:
      - not _http2_push_directive.changed
    fail_msg: http2_push directive is not set in location block.
    success_msg: http2_push directive is set in location block.

- name: Check if http2_push_preload directive is set in location block
  when:
    - _location_block.http2_push_preload is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        http2_push_preload {{ _location_block.http2_push_preload | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_push_preload_directive

- name: Verify http2_push_preload directive is set in location block
  when:
    - _location_block.http2_push is defined
  ansible.builtin.assert:
    that:
      - not _http2_push_preload_directive.changed
    fail_msg: http2_push_preload directive is not set in location block.
    success_msg: http2_push_preload directive is set in location block.
