---
- name: Verify ngx_http_core_module directives
  ansible.builtin.include_tasks: http/server/location/core.yml

- name: Verify ngx_http_v2_module directives
  ansible.builtin.include_tasks: http/server/location/http2.yml

- name: Verify ngx_http_proxy_module directives
  ansible.builtin.include_tasks: http/server/location/proxy.yml

- name: Verify ngx_http_grpc_module directives
  ansible.builtin.include_tasks: http/server/location/grpc.yml

- name: Verify ngx_http_access_module directives
  ansible.builtin.include_tasks: http/server/location/access.yml

- name: Verify ngx_http_auth_basic_module directives
  ansible.builtin.include_tasks: http/server/location/auth_basic.yml

- name: Verify ngx_http_auth_request_module directives
  ansible.builtin.include_tasks: http/server/location/auth_request.yml

- name: Verify ngx_http_auth_jwt_module directives
  ansible.builtin.include_tasks: http/server/location/auth_jwt.yml

- name: Verify ngx_http_stub_status_module directives
  ansible.builtin.include_tasks: http/server/location/stub_status.yml

- name: Verify ngx_http_index_module directives
  ansible.builtin.include_tasks: http/server/location/index.yml

- name: Verify ngx_http_gunzip_module directives
  ansible.builtin.include_tasks: http/server/location/gunzip.yml

- name: Verify ngx_http_gzip_module directives
  ansible.builtin.include_tasks: http/server/location/gzip.yml

- name: Verify ngx_http_headers_module directives
  ansible.builtin.include_tasks: http/server/location/headers.yml

- name: Verify ngx_http_limit_req_module directives
  ansible.builtin.include_tasks: http/server/location/limit_req.yml

- name: Verify ngx_http_log_module directives
  ansible.builtin.include_tasks: http/server/location/log.yml

- name: Verify ngx_http_mirror_module directives
  ansible.builtin.include_tasks: http/server/location/mirror.yml

- name: Verify ngx_http_realip_module directives
  ansible.builtin.include_tasks: http/server/location/realip.yml

- name: Verify ngx_http_rewrite_module directives
  ansible.builtin.include_tasks: http/server/location/rewrite.yml

- name: Check if custom directive is set in location block
  loop: "{{ _location_block.custom_directives | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        {{ item }}"
    owner: root
    group: root
    mode: '0640'
  register: _custom_directive

- name: Verify custom directive is set in location block
  loop: "{{ _custom_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: "Custom directive '{{ item.item }}' is not set in location block."
    success_msg: "Custom directive '{{ item.item }}' is set in location block."
  loop_control:
    label: "{{ item.item }}"

- name: Verify location if block
  loop: "{{ _location_block.if | default([]) }}"
  ansible.builtin.include_tasks: http/server/location/if/main.yml
  loop_control:
    loop_var: _location_block

- name: Verify limit_except block
  loop: "{{ _location_block.limit_except | default([]) }}"
  ansible.builtin.include_tasks: http/server/location/limit_except/main.yml
  loop_control:
    loop_var: _limit_except_block

- name: Verify types block
  when:
    - _location_block.types is defined
  ansible.builtin.include_tasks: http/server/location/types/main.yml

- name: Verify nested location block
  loop: "{{ _location_block.location | default([]) }}"
  ansible.builtin.include_tasks: http/server/location/main.yml
  loop_control:
    loop_var: _location_block
