---
- name: Check if mirror directive is set in location block (off)
  when:
    - _location_block.mirror is defined
    - _location_block.mirror.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        mirror off;"
    owner: root
    group: root
    mode: '0640'
  register: _mirror_off_directive

- name: Verify mirror directive is set in location block (off)
  when:
    - _location_block.mirror is defined
    - _location_block.mirror.off | default(false)
  ansible.builtin.assert:
    that:
      - not _mirror_off_directive.changed
    fail_msg: mirror directive is not set in location block.
    success_msg: mirror directive is set in location block.

- name: Check if mirror directive is set in location block
  loop: "{{ _location_block.mirror.uris | default([]) }}"
  when:
    - _location_block.mirror is defined
    - not _location_block.mirror.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        mirror {{ item }};"
    owner: root
    group: root
    mode: '0640'
  register: _mirror_directive

- name: Verify mirror directive is set in location block
  loop: "{{ _mirror_directive.results }}"
  when:
    - _location_block.mirror is defined
    - not _location_block.mirror.off | default(false)
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: mirror directive is not set in location block.
    success_msg: mirror directive is set in location block.
  loop_control:
    label: "{{ item.item }}"

- name: Check if mirror_request_body directive is set in location block
  when:
    - _location_block.mirror_request_body is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        mirror_request_body {{ _location_block.mirror_request_body | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _mirror_request_body_directive

- name: Verify mirror_request_body directive is set in location block
  when:
    - _location_block.mirror_request_body is defined
  ansible.builtin.assert:
    that:
      - not _mirror_request_body_directive.changed
    fail_msg: mirror_request_body directive is not set in location block.
    success_msg: mirror_request_body directive is set in location block.
