---
- name: Check if proxy_pass directive is set in limit_except block
  when:
    - _limit_except_block.proxy_pass is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        limit_except ({{ _limit_except_block.methods | join(' ') }}) {"
    line: "            proxy_pass {{ _limit_except_block.proxy_pass }};"
    owner: root
    group: root
    mode: '0640'
  register: _proxy_pass_directive

- name: Verify proxy_pass directive is set in limit_except block
  when:
    - _location_if_block.proxy_pass is defined
  ansible.builtin.assert:
    that:
      - not _proxy_pass_directive.changed
    fail_msg: proxy_pass directive is not set in limit_except block.
    success_msg: proxy_pass directive is set in limit_except block.
