---
- name: Verify ngx_http_proxy_module directives
  ansible.builtin.include_tasks: http/server/location/limit_except/proxy.yml

- name: Verify ngx_http_access_module directives
  ansible.builtin.include_tasks: http/server/location/limit_except/access.yml

- name: Verify ngx_http_auth_basic_module directives
  ansible.builtin.include_tasks: http/server/location/limit_except/auth_basic.yml

- name: Verify ngx_http_auth_jwt_module directives
  ansible.builtin.include_tasks: http/server/location/limit_except/auth_jwt.yml

- name: Verify ngx_http_log_module directives
  ansible.builtin.include_tasks: http/server/location/limit_except/log.yml

- name: Check if custom directive is set in limit_except block
  loop: "{{ _location_if_block.custom_directives | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        limit_except ({{ _limit_except_block.methods | join(' ') }}) {"
    line: "            {{ item }}"
    owner: root
    group: root
    mode: '0640'
  register: _custom_directive

- name: Verify custom directive is set in limit_except block
  loop: "{{ _custom_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: "Custom directive '{{ item.item }}' is not set in limit_except block."
    success_msg: "Custom directive '{{ item.item }}' is set in limit_except block."
  loop_control:
    label: "{{ item.item }}"
