---
- name: Check if directive is set in split_clients block
  loop: "{{ _split_clients_block.contents | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "split_clients {{ _split_clients_block.string }} {{ _split_clients_block.variable }} {"
    line: "    {{ item.percentage }} {{ item.value }};"
    owner: root
    group: root
    mode: '0640'
  register: _content_directive

- name: Verify directive is set in split_clients block
  loop: "{{ _content_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: Directive is not set in split_clients block.
    success_msg: Directive is set in split_clients block.
  loop_control:
    label: "{{ item.item }}"

- name: Check if custom directive is set in split_clients block
  loop: "{{ _split_clients_block.custom_directives | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "split_clients {{ _split_clients_block.string }} {{ _split_clients_block.variable }} {"
    line: "    {{ item }}"
    owner: root
    group: root
    mode: '0640'
  register: _custom_directive

- name: Verify custom directive is set in split_clients block
  loop: "{{ _custom_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: "Custom directive '{{ item.item }}' is not set in split_clients block."
    success_msg: "Custom directive '{{ item.item }}' is set in split_clients block."
  loop_control:
    label: "{{ item.item }}"
