---
- name: Check if auth_basic directive is set in server block
  when:
    - _server_block.auth_basic is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    auth_basic {{ _server_block.auth_basic }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_basic_directive

- name: Verify auth_basic directive is set in server block
  when:
    - _server_block.auth_basic is defined
  ansible.builtin.assert:
    that:
      - not _auth_basic_directive.changed
    fail_msg: auth_basic directive is not set in server block.
    success_msg: auth_basic directive is set in server block.

- name: Check if auth_basic_user_file directive is set in server block
  when:
    - _server_block.auth_basic_user_file is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    auth_basic_user_file {{ _server_block.auth_basic_user_file }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_basic_user_file_directive

- name: Verify auth_basic_user_file directive is set in server block
  when:
    - _server_block.auth_basic_user_file is defined
  ansible.builtin.assert:
    that:
      - not _auth_basic_user_file_directive.changed
    fail_msg: auth_basic_user_file directive is not set in server block.
    success_msg: auth_basic_user_file directive is set in server block.
