---
- name: Check if gunzip directive is set in server block
  when:
    - _server_block.gunzip is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    gunzip {{ _server_block.gunzip | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _gunzip_directive

- name: Verify gunzip directive is set in server block
  when:
    - _server_block.gunzip is defined
  ansible.builtin.assert:
    that:
      - not _gunzip_directive.changed
    fail_msg: gunzip directive is not set in server block.
    success_msg: gunzip directive is set in server block.

- name: Check if gunzip_buffers directive is set in server block
  when:
    - _server_block.gunzip_buffers is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    gunzip_buffers {{ _server_block.gunzip_buffers.number }} {{ _server_block.gunzip_buffers.size }};"
    owner: root
    group: root
    mode: '0640'
  register: _gunzip_buffers_directive

- name: Verify gunzip_buffers directive is set in server block
  when:
    - _server_block.gunzip_buffers is defined
  ansible.builtin.assert:
    that:
      - not _gunzip_buffers_directive.changed
    fail_msg: gunzip_buffers directive is not set in server block.
    success_msg: gunzip_buffers directive is set in server block.
