---
- name: Check if add_header directive is set in server block
  loop: "{{ _server_block.add_header | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    add_header {{ item.field }} {{ item.value }}{{ ' always' if item.always | default(false) }};"
    owner: root
    group: root
    mode: '0640'
  register: _add_header_directive

- name: Verify add_header directive is set in server block
  loop: "{{ _add_header_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: add_header directive is not set in server block.
    success_msg: add_header directive is set in server block.
  loop_control:
    label: "{{ item.item }}"

- name: Check if add_trailer directive is set in server block
  loop: "{{ _server_block.add_trailer | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    add_trailer {{ item.field }} {{ item.value }}{{ ' always' if item.always | default(false) }};"
    owner: root
    group: root
    mode: '0640'
  register: _add_trailer_directive

- name: Verify add_trailer directive is set in server block
  loop: "{{ _add_header_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: add_trailer directive is not set in server block.
    success_msg: add_trailer directive is set in server block.
  loop_control:
    label: "{{ item.item }}"

- name: Check if expires directive is set in server block (off)
  when:
    - _server_block.expires is defined
    - _server_block.expires.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    expires off;"
    owner: root
    group: root
    mode: '0640'
  register: _expires_off_directive

- name: Verify expires directive is set in server block (off)
  when:
    - _server_block.expires is defined
    - _server_block.expires.off | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_off_directive.changed
    fail_msg: expires directive is not set in server block.
    success_msg: expires directive is set in server block.

- name: Check if expires directive is set in server block (max)
  when:
    - _server_block.expires is defined
    - not _server_block.expires.off | default(false)
    - _server_block.expires.max | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    expires max;"
    owner: root
    group: root
    mode: '0640'
  register: _expires_max_directive

- name: Verify expires directive is set in server block (max)
  when:
    - _server_block.expires is defined
    - not _server_block.expires.off | default(false)
    - _server_block.expires.max | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_max_directive.changed
    fail_msg: expires directive is not set in server block.
    success_msg: expires directive is set in server block.

- name: Check if expires directive is set in server block (epoch)
  when:
    - _server_block.expires is defined
    - not _server_block.expires.off | default(false)
    - not _server_block.expires.max | default(false)
    - _server_block.expires.epoch | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    expires epoch;"
    owner: root
    group: root
    mode: '0640'
  register: _expires_epoch_directive

- name: Verify expires directive is set in server block (epoch)
  when:
    - _server_block.expires is defined
    - not _server_block.expires.off | default(false)
    - not _server_block.expires.max | default(false)
    - _server_block.expires.epoch | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_epoch_directive.changed
    fail_msg: expires directive is not set in server block.
    success_msg: expires directive is set in server block.

- name: Check if expires directive is set in server block
  when:
    - _server_block.expires is defined
    - not _server_block.expires.off | default(false)
    - not _server_block.expires.max | default(false)
    - not _server_block.expires.epoch | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: >-
      {{ '    ' }}expires {{ 'modified ' if _server_block.expires.modified | default(false) -}}
        {{- _server_block.expires.time }};
    owner: root
    group: root
    mode: '0640'
  register: _expires_directive

- name: Verify expires directive is set in server block
  when:
    - _server_block.expires is defined
    - not _server_block.expires.off | default(false)
    - not _server_block.expires.max | default(false)
    - not _server_block.expires.epoch | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_directive.changed
    fail_msg: expires directive is not set in server block.
    success_msg: expires directive is set in server block.
