---
- name: Verify ngx_http_core_module directives
  ansible.builtin.include_tasks: http/server/core.yml

- name: Verify ngx_http_v2_module directives
  ansible.builtin.include_tasks: http/server/http2.yml

- name: Verify ngx_http_ssl_module directives
  ansible.builtin.include_tasks: http/server/ssl.yml

- name: Verify ngx_http_proxy_module directives
  ansible.builtin.include_tasks: http/server/proxy.yml

- name: Verify ngx_http_grpc_module directives
  ansible.builtin.include_tasks: http/server/grpc.yml

- name: Verify ngx_http_access_module directives
  ansible.builtin.include_tasks: http/server/access.yml

- name: Verify ngx_http_auth_basic_module directives
  ansible.builtin.include_tasks: http/server/auth_basic.yml

- name: Verify ngx_http_auth_request_module directives
  ansible.builtin.include_tasks: http/server/auth_request.yml

- name: Verify ngx_http_auth_jwt_module directives
  ansible.builtin.include_tasks: http/server/auth_jwt.yml

- name: Verify ngx_http_stub_status_module directives
  ansible.builtin.include_tasks: http/server/stub_status.yml

- name: Verify ngx_http_index_module directives
  ansible.builtin.include_tasks: http/server/index.yml

- name: Verify ngx_http_gunzip_module directives
  ansible.builtin.include_tasks: http/server/gunzip.yml

- name: Verify ngx_http_gzip_module directives
  ansible.builtin.include_tasks: http/server/gzip.yml

- name: Verify ngx_http_headers_module directives
  ansible.builtin.include_tasks: http/server/headers.yml

- name: Verify ngx_http_limit_req_module directives
  ansible.builtin.include_tasks: http/server/limit_req.yml

- name: Verify ngx_http_log_module directives
  ansible.builtin.include_tasks: http/server/log.yml

- name: Verify ngx_http_mirror_module directives
  ansible.builtin.include_tasks: http/server/mirror.yml

- name: Verify ngx_http_realip_module directives
  ansible.builtin.include_tasks: http/server/realip.yml

- name: Verify ngx_http_rewrite_module directives
  ansible.builtin.include_tasks: http/server/rewrite.yml

- name: Verify ngx_http_sub_filter_module directives
  ansible.builtin.include_tasks: http/server/sub_filter.yml

- name: Check if custom directive is set in server block
  loop: "{{ _server_block.custom_directives | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    {{ item }}"
    owner: root
    group: root
    mode: '0640'
  register: _custom_directive

- name: Verify custom directive is set in server block
  loop: "{{ _custom_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: "Custom directive '{{ item.item }}' is not set in server block."
    success_msg: "Custom directive '{{ item.item }}' is set in server block."
  loop_control:
    label: "{{ item.item }}"

- name: Verify location block
  loop: "{{ _server_block.location | default([]) }}"
  ansible.builtin.include_tasks: http/server/location/main.yml
  loop_control:
    loop_var: _location_block

- name: Verify server if block
  loop: "{{ _server_block.if | default([]) }}"
  ansible.builtin.include_tasks: http/server/if/main.yml
  loop_control:
    loop_var: _server_if_block

- name: Verify types block
  when:
    - _server_block.types is defined
  ansible.builtin.include_tasks: http/server/types/main.yml
