---
- name: Check if stub_status directive is set in server block
  when:
    - _server_block.stub_status | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    stub_status;"
    owner: root
    group: root
    mode: '0640'
  register: _stub_status_directive

- name: Verify stub_status directive is set in server block
  when:
    - _server_block.stub_status | default(false)
  ansible.builtin.assert:
    that:
      - not _stub_status_directive.changed
    fail_msg: stub_status directive is not set in server block.
    success_msg: stub_status directive is set in server block.
