---
- name: Check if sub_filter directive is set in server block
  loop: "{{ _server_block.sub_filter | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    sub_filter {{ item.pattern }} {{ item.replacement }};"
    owner: root
    group: root
    mode: '0640'
  register: _sub_filter_directive

- name: Verify sub_filter directive is set in server block
  loop: "{{ _sub_filter_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: sub_filter directive is not set in server block.
    success_msg: sub_filter directive is set in server block.
  loop_control:
    label: "{{ item.item }}"
