---
namespace: trippsc2
name: nginx
version: 1.1.2
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains roles for configuring NGINX.

license_file: 'LICENSE'

tags:
  - infrastructure
  - linux

dependencies:
  ansible.posix: '>=1.0.0'
  community.general: '>=1.0.0'
  trippsc2.general: '>=2.2.0'

repository: https://github.com/trippsc2/ansible-collection-nginx.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
