---
namespace: trippsc2
name: nginx
version: 1.1.4
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains roles for configuring NGINX.

license_file: 'LICENSE'

tags:
  - infrastructure
  - linux

dependencies:
  ansible.posix: '>=1.0.1'
  ansible.utils: '>=2.5.0'
  community.general: '>=9.5.5'

repository: https://github.com/trippsoft/ansible-collection-nginx.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
