---
namespace: trippsc2
name: nginx
version: 1.0.0
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains roles for configuring NGINX.

license_file: 'LICENSE'

tags: []

dependencies: {}

repository: https://github.com/trippsc2/ansible-collection-nginx.git

build_ignore:
  - .gitignore
