---
nginxproxy_additional_http_config_files: []

nginxproxy_redirect_server_name: _
nginxproxy_redirect_return_server_name: $host
nginxproxy_max_body_size: 100K

nginxproxy_ssl_stapling: true
nginxproxy_ssl_stapling_verify: true
