---
- name: Validate ngx_http_core_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/core.yml

- name: Validate ngx_http_v2_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/http2.yml

- name: Validate ngx_http_proxy_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/proxy.yml

- name: Validate ngx_http_grpc_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/grpc.yml

- name: Validate ngx_http_access_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/access.yml

- name: Validate ngx_http_auth_basic_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/auth_basic.yml

- name: Validate ngx_http_auth_request_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/auth_request.yml

- name: Validate ngx_http_auth_jwt_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/auth_jwt.yml

- name: Validate ngx_http_gunzip_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/gunzip.yml

- name: Validate ngx_http_gzip_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/gzip.yml

- name: Validate ngx_http_headers_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/headers.yml

- name: Validate ngx_http_limit_req_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/limit_req.yml

- name: Validate ngx_http_log_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/log.yml

- name: Validate ngx_http_realip_module variables in location block
  ansible.builtin.include_tasks: validate/http/location/realip.yml

- name: Validate if block in location block
  loop: "{{ _nginx_location_block.if | default([]) }}"
  ansible.builtin.include_tasks: validate/http/location/if/main.yml
  loop_control:
    loop_var: _nginx_if_block

- name: Validate limit_except block in location block
  loop: "{{ _nginx_location_block.limit_except | default([]) }}"
  ansible.builtin.include_tasks: validate/http/location/limit_except/main.yml
  loop_control:
    loop_var: _nginx_limit_except_block

- name: Validate nested location blocks by argument spec
  ansible.builtin.validate_argument_spec:
    argument_spec: >-
      {{ (lookup('ansible.builtin.file', 'meta/argument_specs.yml') | from_yaml)
            .argument_specs
            .main
            .options
            .nginx_http_config_files
            .options
            .server
            .options }}
    provided_arguments:
      location: "{{ _nginx_location_block.location | default([]) }}"

- name: Validate location block in location block
  loop: "{{ _nginx_location_block.location | default([]) }}"
  ansible.builtin.include_tasks: validate/http/location/main.yml
  loop_control:
    loop_var: _nginx_location_block
