---
- name: Verify ngx_http_core_module directives
  ansible.builtin.include_tasks: http/server/if/rewrite.yml

- name: Check if custom directive is set in server if block
  loop: "{{ _location_if_block.custom_directives | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "    if ({{ _server_if_block.condition }}) {"
    line: "        {{ item }}"
    owner: root
    group: root
    mode: '0640'
  register: _custom_directive

- name: Verify custom directive is set in server if block
  loop: "{{ _custom_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: "Custom directive '{{ item.item }}' is not set in server if block."
    success_msg: "Custom directive '{{ item.item }}' is set in server if block."
  loop_control:
    label: "{{ item.item }}"
