---
- name: Validate map_hash_bucket_size in HTTP config file
  when:
    - _nginx_http_config_file.map_hash_bucket_size is defined
  ansible.builtin.assert:
    that:
      - _nginx_http_config_file.map_hash_bucket_size | int > 0
    fail_msg: "Directive 'map_hash_bucket_size' in '{{ _nginx_http_config_file.destination }}' is not a positive integer. Value: {{ _nginx_http_config_file.map_hash_bucket_size }}"
    success_msg: "Directive 'map_hash_bucket_size' in '{{ _nginx_http_config_file.destination }}' is valid. Value: {{ _nginx_http_config_file.map_hash_bucket_size }}"

- name: Validate map_hash_max_size in HTTP config file
  when:
    - _nginx_http_config_file.map_hash_max_size is defined
  ansible.builtin.assert:
    that:
      - _nginx_http_config_file.map_hash_max_size | int > 0
    fail_msg: "Directive 'map_hash_max_size' in '{{ _nginx_http_config_file.destination }}' is not a positive integer. Value: {{ _nginx_http_config_file.map_hash_max_size }}"
    success_msg: "Directive 'map_hash_max_size' in '{{ _nginx_http_config_file.destination }}' is valid. Value: {{ _nginx_http_config_file.map_hash_max_size }}"
