---
- name: Ensure SELinux management packages are installed
  become: true
  ansible.builtin.package:
    name: "{{ _nginx_selinux_packages }}"
    state: present

- name: Ensure SELinux is configured to allow HTTP network connections
  loop:
    - httpd_can_network_connect
    - httpd_can_network_relay
  become: true
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true

- name: Ensure TCP ports are classified as http_port_t
  become: true
  community.general.seport:
    ports: "{{ nginx_tcp_ports }}"
    proto: tcp
    setype: http_port_t
    state: present
    reload: true

- name: Ensure UDP ports are classified as http_port_t
  become: true
  community.general.seport:
    ports: "{{ nginx_udp_ports }}"
    proto: udp
    setype: http_port_t
    state: present
    reload: true
