---
- name: Check if allow directive is set in HTTP config file
  loop: "{{ _http_config_file.allow | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "allow {{ item }};"
    owner: root
    group: root
    mode: '0640'
  register: _allow_directive

- name: Verify allow directive is set in HTTP config file
  loop: "{{ _allow_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: allow directive is not set in HTTP config file.
    success_msg: allow directive is set in HTTP config file.
  loop_control:
    label: "{{ item.item }}"

- name: Check if deny directive is set in HTTP config file
  loop: "{{ _http_config_file.deny | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "deny {{ item }};"
    owner: root
    group: root
    mode: '0640'
  register: _deny_directive

- name: Verify deny directive is set in HTTP config file
  loop: "{{ _deny_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: deny directive is not set in HTTP config file.
    success_msg: deny directive is set in HTTP config file.
  loop_control:
    label: "{{ item.item }}"
