---
- name: Check if gunzip directive is set in HTTP config file
  when:
    - _http_config_file.gunzip is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "gunzip {{ _http_config_file.gunzip | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _gunzip_directive

- name: Verify gunzip directive is set in HTTP config file
  when:
    - _http_config_file.gunzip is defined
  ansible.builtin.assert:
    that:
      - not _gunzip_directive.changed
    fail_msg: gunzip directive is not set in HTTP config file.
    success_msg: gunzip directive is set in HTTP config file.

- name: Check if gunzip_buffers directive is set in HTTP config file
  when:
    - _http_config_file.gunzip_buffers is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "gunzip_buffers {{ _http_config_file.gunzip_buffers.number }} {{ _http_config_file.gunzip_buffers.size }};"
    owner: root
    group: root
    mode: '0640'
  register: _gunzip_buffers_directive

- name: Verify gunzip_buffers directive is set in HTTP config file
  when:
    - _http_config_file.gunzip_buffers is defined
  ansible.builtin.assert:
    that:
      - not _gunzip_buffers_directive.changed
    fail_msg: gunzip_buffers directive is not set in HTTP config file.
    success_msg: gunzip_buffers directive is set in HTTP config file.
