---
- name: Check if http2_chunk_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_chunk_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_chunk_size {{ _http_config_file.http2_chunk_size }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_chunk_size_directive

- name: Verify http2_chunk_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_chunk_size is defined
  ansible.builtin.assert:
    that:
      - not _http2_chunk_size_directive.changed
    fail_msg: http2_chunk_size directive is not set in HTTP config file.
    success_msg: http2_chunk_size directive is set in HTTP config file.

- name: Check if http2_push directive is set in HTTP config file
  when:
    - _http_config_file.http2_push is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_push {{ _http_config_file.http2_push }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_push_directive

- name: Verify http2_push directive is set in HTTP config file
  when:
    - _http_config_file.http2_push is defined
  ansible.builtin.assert:
    that:
      - not _http2_push_directive.changed
    fail_msg: http2_push directive is not set in HTTP config file.
    success_msg: http2_push directive is set in HTTP config file.

- name: Check if http2_push_preload directive is set in HTTP config file
  when:
    - _http_config_file.http2_push_preload is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_push_preload {{ _http_config_file.http2_push_preload | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_push_preload_directive

- name: Verify http2_push_preload directive is set in HTTP config file
  when:
    - _http_config_file.http2_push is defined
  ansible.builtin.assert:
    that:
      - not _http2_push_preload_directive.changed
    fail_msg: http2_push_preload directive is not set in HTTP config file.
    success_msg: http2_push_preload directive is set in HTTP config file.

- name: Check if http2_body_preread_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_body_preread_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_body_preread_size {{ _http_config_file.http2_body_preread_size }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_body_preread_size_directive

- name: Verify http2_body_preread_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_body_preread_size is defined
  ansible.builtin.assert:
    that:
      - not _http2_body_preread_size_directive.changed
    fail_msg: http2_body_preread_size directive is not set in HTTP config file.
    success_msg: http2_body_preread_size directive is set in HTTP config file.

- name: Check if http2_idle_timeout directive is set in HTTP config file
  when:
    - _http_config_file.http2_idle_timeout is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_idle_timeout {{ _http_config_file.http2_idle_timeout }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_idle_timeout_directive

- name: Verify http2_idle_timeout directive is set in HTTP config file
  when:
    - _http_config_file.http2_idle_timeout is defined
  ansible.builtin.assert:
    that:
      - not _http2_idle_timeout_directive.changed
    fail_msg: http2_idle_timeout directive is not set in HTTP config file.
    success_msg: http2_idle_timeout directive is set in HTTP config file.

- name: Check if http2_max_concurrent_pushes directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_concurrent_pushes is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_max_concurrent_pushes {{ _http_config_file.http2_max_concurrent_pushes }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_max_concurrent_pushes_directive

- name: Verify http2_max_concurrent_pushes directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_concurrent_pushes is defined
  ansible.builtin.assert:
    that:
      - not _http2_max_concurrent_pushes_directive.changed
    fail_msg: http2_max_concurrent_pushes directive is not set in HTTP config file.
    success_msg: http2_max_concurrent_pushes directive is set in HTTP config file.

- name: Check if http2_max_concurrent_streams directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_concurrent_streams is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_max_concurrent_streams {{ _http_config_file.http2_max_concurrent_streams }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_max_concurrent_streams_directive

- name: Verify http2_max_concurrent_streams directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_concurrent_streams is defined
  ansible.builtin.assert:
    that:
      - not _http2_max_concurrent_streams_directive.changed
    fail_msg: http2_max_concurrent_streams directive is not set in HTTP config file.
    success_msg: http2_max_concurrent_streams directive is set in HTTP config file.

- name: Check if http2_max_field_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_field_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_max_field_size {{ _http_config_file.http2_max_field_size }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_max_field_size_directive

- name: Verify http2_max_field_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_field_size is defined
  ansible.builtin.assert:
    that:
      - not _http2_max_field_size_directive.changed
    fail_msg: http2_max_field_size directive is not set in HTTP config file.
    success_msg: http2_max_field_size directive is set in HTTP config file.

- name: Check if http2_max_header_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_header_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_max_header_size {{ _http_config_file.http2_max_header_size }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_max_header_size_directive

- name: Verify http2_max_header_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_header_size is defined
  ansible.builtin.assert:
    that:
      - not _http2_max_header_size_directive.changed
    fail_msg: http2_max_header_size directive is not set in HTTP config file.
    success_msg: http2_max_header_size directive is set in HTTP config file.

- name: Check if http2_max_requests directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_requests is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_max_requests {{ _http_config_file.http2_max_requests }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_max_requests_directive

- name: Verify http2_max_requests directive is set in HTTP config file
  when:
    - _http_config_file.http2_max_requests is defined
  ansible.builtin.assert:
    that:
      - not _http2_max_requests_directive.changed
    fail_msg: http2_max_requests directive is not set in HTTP config file.
    success_msg: http2_max_requests directive is set in HTTP config file.

- name: Check if http2_recv_timeout directive is set in HTTP config file
  when:
    - _http_config_file.http2_recv_timeout is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_recv_timeout {{ _http_config_file.http2_recv_timeout }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_recv_timeout_directive

- name: Verify http2_recv_timeout directive is set in HTTP config file
  when:
    - _http_config_file.http2_recv_timeout is defined
  ansible.builtin.assert:
    that:
      - not _http2_recv_timeout_directive.changed
    fail_msg: http2_recv_timeout directive is not set in HTTP config file.
    success_msg: http2_recv_timeout directive is set in HTTP config file.

- name: Check if http2_recv_buffer_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_recv_buffer_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "http2_recv_buffer_size {{ _http_config_file.http2_recv_buffer_size }};"
    owner: root
    group: root
    mode: '0640'
  register: _http2_recv_buffer_size_directive

- name: Verify http2_recv_buffer_size directive is set in HTTP config file
  when:
    - _http_config_file.http2_recv_buffer_size is defined
  ansible.builtin.assert:
    that:
      - not _http2_recv_buffer_size_directive.changed
    fail_msg: http2_recv_buffer_size directive is not set in HTTP config file.
    success_msg: http2_recv_buffer_size directive is set in HTTP config file.
