---
- name: Check if autoindex directive is set in HTTP config file
  when:
    - _http_config_file.autoindex is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "autoindex {{ _http_config_file.autoindex | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _autoindex_directive

- name: Verify autoindex directive is set in HTTP config file
  when:
    - _http_config_file.autoindex is defined
  ansible.builtin.assert:
    that:
      - not _autoindex_directive.changed
    fail_msg: autoindex directive is not set in HTTP config file.
    success_msg: autoindex directive is set in HTTP config file.

- name: Check if autoindex_exact_size directive is set in HTTP config file
  when:
    - _http_config_file.autoindex_exact_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "autoindex_exact_size {{ _http_config_file.autoindex_exact_size | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _autoindex_exact_size_directive

- name: Verify autoindex_exact_size directive is set in HTTP config file
  when:
    - _http_config_file.autoindex_exact_size is defined
  ansible.builtin.assert:
    that:
      - not _autoindex_exact_size_directive.changed
    fail_msg: autoindex_exact_size directive is not set in HTTP config file.
    success_msg: autoindex_exact_size directive is set in HTTP config file.

- name: Check if autoindex_format directive is set in HTTP config file
  when:
    - _http_config_file.autoindex_format is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "autoindex_format {{ _http_config_file.autoindex_format }};"
    owner: root
    group: root
    mode: '0640'
  register: _autoindex_format_directive

- name: Verify autoindex_format directive is set in HTTP config file
  when:
    - _http_config_file.autoindex_format is defined
  ansible.builtin.assert:
    that:
      - not _autoindex_format_directive.changed
    fail_msg: autoindex_format directive is not set in HTTP config file.
    success_msg: autoindex_format directive is set in HTTP config file.

- name: Check if autoindex_localtime directive is set in HTTP config file
  when:
    - _http_config_file.autoindex_localtime is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "autoindex_localtime {{ _http_config_file.autoindex_localtime | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _autoindex_localtime_directive

- name: Verify autoindex_localtime directive is set in HTTP config file
  when:
    - _http_config_file.autoindex_localtime is defined
  ansible.builtin.assert:
    that:
      - not _autoindex_localtime_directive.changed
    fail_msg: autoindex_localtime directive is not set in HTTP config file.
    success_msg: autoindex_localtime directive is set in HTTP config file.

- name: Check if index directive is set in HTTP config file
  when:
    - _http_config_file.index is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "index {{ _http_config_file.index | join(' ') }};"
    owner: root
    group: root
    mode: '0640'
  register: _index_directive

- name: Verify index directive is set in HTTP config file
  when:
    - _http_config_file.index is defined
  ansible.builtin.assert:
    that:
      - not _index_directive.changed
    fail_msg: index directive is not set in HTTP config file.
    success_msg: index directive is set in HTTP config file.

- name: Check if random_index directive is set in HTTP config file
  when:
    - _http_config_file.random_index is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "random_index {{ _http_config_file.random_index | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _random_index_directive

- name: Verify random_index directive is set in HTTP config file
  when:
    - _http_config_file.random_index is defined
  ansible.builtin.assert:
    that:
      - not _random_index_directive.changed
    fail_msg: random_index directive is not set in HTTP config file.
    success_msg: random_index directive is set in HTTP config file.
