---
- name: Check if map_hash_bucket_size directive is set in HTTP config file
  when:
    - _http_config_file.map_hash_bucket_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "map_hash_bucket_size {{ _http_config_file.map_hash_bucket_size }};"
    owner: root
    group: root
    mode: '0640'
  register: _map_hash_bucket_size_directive

- name: Verify map_hash_bucket_size directive is set in HTTP config file
  when:
    - _http_config_file.map_hash_bucket_size is defined
  ansible.builtin.assert:
    that:
      - not _map_hash_bucket_size_directive.changed
    fail_msg: map_hash_bucket_size directive is not set in HTTP config file.
    success_msg: map_hash_bucket_size directive is set in HTTP config file.

- name: Check if map_hash_max_size directive is set in HTTP config file
  when:
    - _http_config_file.map_hash_max_size is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "map_hash_max_size {{ _http_config_file.map_hash_max_size }};"
    owner: root
    group: root
    mode: '0640'
  register: _map_hash_max_size_directive

- name: Verify map_hash_max_size directive is set in HTTP config file
  when:
    - _http_config_file.map_hash_max_size is defined
  ansible.builtin.assert:
    that:
      - not _map_hash_max_size_directive.changed
    fail_msg: map_hash_max_size directive is not set in HTTP config file.
    success_msg: map_hash_max_size directive is set in HTTP config file.
