---
- name: Check if directive is set in types block
  loop: "{{ _server_block.types | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "    types {"
    line: "        {{ item.mime }} {{ item.extensions | join(' ') }};"
    owner: root
    group: root
    mode: '0640'
  register: _types_directive

- name: Verify directive is set in types block
  loop: "{{ _types_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: Directive is not set in types block.
    success_msg: Directive is set in types block.
  loop_control:
    label: "{{ item.item }}"
