---
- name: Check if auth_request directive is set in server block
  when:
    - _server_block.auth_request is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    auth_request {{ _server_block.auth_request }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_request_directive

- name: Verify auth_request directive is set in server block
  when:
    - _server_block.auth_request is defined
  ansible.builtin.assert:
    that:
      - not _auth_request_directive.changed
    fail_msg: auth_request directive is not set in server block.
    success_msg: auth_request directive is set in server block.

- name: Check if auth_request_set directive is set in server block
  loop: "{{ _server_block.auth_request_set | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    auth_request_set {{ item.variable }} {{ item.value }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_request_set_directive

- name: Verify auth_request_set directive is set in server block
  loop: "{{ _auth_request_set_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: auth_request_set directive is not set in server block.
    success_msg: auth_request_set directive is set in server block.
  loop_control:
    label: "{{ item.item }}"
