---
- name: Check if set_real_ip_from directive is set in server block
  loop: "{{ _server_block.set_real_ip_from | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    set_real_ip_from {{ item }};"
    owner: root
    group: root
    mode: '0640'
  register: _set_real_ip_from_directive

- name: Verify set_real_ip_from directive is set in server block
  loop: "{{ _set_real_ip_from_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: set_real_ip_from directive is not set in server block.
    success_msg: set_real_ip_from directive is set in server block.

- name: Check if real_ip_header directive is set in server block
  when:
    - _server_block.real_ip_header is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    real_ip_header {{ _server_block.real_ip_header }};"
    owner: root
    group: root
    mode: '0640'
  register: _real_ip_header_directive

- name: Verify real_ip_header directive is set in server block
  when:
    - _server_block.real_ip_header is defined
  ansible.builtin.assert:
    that:
      - not _real_ip_header_directive.changed
    fail_msg: real_ip_header directive is not set in server block.
    success_msg: real_ip_header directive is set in server block.

- name: Check if real_ip_recursive directive is set in server block
  when:
    - _server_block.real_ip_recursive is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: server {
    line: "    real_ip_recursive {{ _server_block.real_ip_recursive | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _real_ip_recursive_directive

- name: Verify real_ip_recursive directive is set in server block
  when:
    - _server_block.real_ip_recursive is defined
  ansible.builtin.assert:
    that:
      - not _real_ip_recursive_directive.changed
    fail_msg: real_ip_recursive directive is not set in server block.
    success_msg: real_ip_recursive directive is set in server block.
