---
- name: Validate burst in limit_req in server block
  loop: "{{ _nginx_server_block.limit_req | default([]) }}"
  when:
    - item.burst is defined
  ansible.builtin.assert:
    that:
      - item.burst | int > 0
    fail_msg: "Directive 'burst' in 'limit_req' in server block in '{{ _nginx_http_config_file.destination }}' is not a positive integer. Value: {{ item.burst }}"
    success_msg: "Directive 'burst' in 'limit_req' in server block in '{{ _nginx_http_config_file.destination }}' is valid. Value: {{ item.burst }}"

- name: Validate delay in limit_req in server block
  loop: "{{ _nginx_server_block.limit_req | default([]) }}"
  when:
    - item.delay is defined
  ansible.builtin.assert:
    that:
      - item.delay | int > 0
    fail_msg: "Directive 'delay' in 'limit_req' in server block in '{{ _nginx_http_config_file.destination }}' is not a positive integer. Value: {{ item.delay }}"
    success_msg: "Directive 'delay' in 'limit_req' in server block in '{{ _nginx_http_config_file.destination }}' is valid. Value: {{ item.delay }}"
