---
- name: Validate ngx_http_core_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/core.yml

- name: Validate ngx_http_v2_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/http2.yml

- name: Validate ngx_http_ssl_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/ssl.yml

- name: Validate ngx_http_proxy_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/proxy.yml

- name: Validate ngx_http_grpc_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/grpc.yml

- name: Validate ngx_http_access_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/access.yml

- name: Validate ngx_http_auth_basic_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/auth_basic.yml

- name: Validate ngx_http_auth_request_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/auth_request.yml

- name: Validate ngx_http_auth_jwt_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/auth_jwt.yml

- name: Validate ngx_http_gunzip_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/gunzip.yml

- name: Validate ngx_http_gzip_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/gzip.yml

- name: Validate ngx_http_headers_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/headers.yml

- name: Validate ngx_http_limit_req_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/limit_req.yml

- name: Validate ngx_http_log_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/log.yml

- name: Validate ngx_http_realip_module variables in server block
  ansible.builtin.include_tasks: validate/http/server/realip.yml

- name: Validate location block in server block
  loop: "{{ _nginx_server_block.location | default([]) }}"
  ansible.builtin.include_tasks: validate/http/location/main.yml
  loop_control:
    loop_var: _nginx_location_block
