---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 2048
    cpus: 2
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        nginxproxy_ssl_stapling: false
        nginxproxy_ssl_stapling_verify: false
        nginxproxy_server_name: localhost
        nginxproxy_proxy_address: http://127.0.0.1:8080
verifier:
  name: ansible
