---
- name: Prepare
  hosts:
    - subjects
  pre_tasks:
    - name: Bootstrap python for Ansible
      become: true
      ansible.builtin.raw: |
        command -v python3 python || (
        command -v apk >/dev/null && sudo apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && sudo dnf install -y python3) ||
        (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal)) ||
        (test -e /usr/bin/yum && sudo yum -y -qq install python3) ||
        (test -e /usr/sbin/pkg && sudo env ASSUME_ALWAYS_YES=yes pkg update && sudo env ASSUME_ALWAYS_YES=yes pkg install python3) ||
        (test -e /usr/sbin/pkg_add && sudo /usr/sbin/pkg_add -U -I -x python%3.7) ||
        echo "Warning: Python not bootstrapped due to unknown platform."
        )
      changed_when: false
    
    - name: Set OS specific variables (Debian-based)
      when:
        - ansible_os_family == 'Debian'
      ansible.builtin.set_fact:
        _apache_package: apache2
        _apache_config_file_path: /etc/apache2/ports.conf
        _apache_service: apache2.service
        _cert_certificate_path: /etc/ssl/certs/nginx.crt
        _cert_private_key_path: /etc/ssl/private/nginx.key
    
    - name: Set OS specific variables (RHEL-based)
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.set_fact:
        _apache_package: httpd
        _apache_config_file_path: /etc/httpd/conf/httpd.conf
        _apache_service: httpd.service
        _cert_certificate_path: /etc/pki/tls/certs/nginx.crt
        _cert_private_key_path: /etc/pki/tls/private/nginx.key

    - name: Install Apache as a target to be proxied
      become: true
      ansible.builtin.package:
        name:
          - "{{ _apache_package }}"
        state: present
    
    - name: Configure Apache to listen on localhost port 8080
      become: true
      ansible.builtin.lineinfile:
        path: "{{ _apache_config_file_path }}"
        line: Listen 127.0.0.1:8080
        regexp: '^Listen'

    - name: Configure Apache virtual host for port 8080 (Debian-based)
      when:
        - ansible_os_family == 'Debian'
      become: true
      ansible.builtin.lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        line: <VirtualHost *:8080>
        regexp: '^<VirtualHost \*:80>'

    - name: Restart Apache service
      become: true
      ansible.builtin.systemd_service:
        name: "{{ _apache_service }}"
        state: restarted
  roles:
    - role: trippsc2.general.self_signed_certificate
      vars:
        cert_certificate_path: "{{ _cert_certificate_path }}"
        cert_private_key_path: "{{ _cert_private_key_path }}"
        cert_private_key_mode: '0400'
        cert_common_name: localhost
        cert_subject_alternative_names:
          - 'DNS:localhost'
          - 'IP:127.0.0.1'
