---

- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Check if NGINX is installed
      become: true
      check_mode: true
      ansible.builtin.package:
        name:
          - nginx
        state: present
      register: _package

    - name: Verify NGINX is installed
      ansible.builtin.assert:
        that:
          - not _package.changed
        fail_msg: NGINX is not installed.
        success_msg: NGINX is installed.

    - name: Check if NGINX service is enabled
      become: true
      check_mode: true
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
      register: _service_enabled

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _service_enabled.changed
        fail_msg: NGINX service is not enabled.
        success_msg: NGINX service is enabled.

    - name: Check if NGINX service is running
      become: true
      check_mode: true
      ansible.builtin.systemd_service:
        name: nginx
        state: started
      register: _service_running

    - name: Verify NGINX service is running
      ansible.builtin.assert:
        that:
          - not _service_running.changed
        fail_msg: NGINX service is not running.
        success_msg: NGINX service is running.

    - name: Check ss output
      ansible.builtin.command: ss -tuln
      changed_when: false
      register: _ss_output

    - name: Verify that NGINX is listening on port 80
      ansible.builtin.assert:
        that:
          - '"0.0.0.0:80" in _ss_output.stdout'
        fail_msg: NGINX not listening on port 80.
        success_msg: NGINX listening on port 80.

    - name: Verify that NGINX is listening on port 443
      ansible.builtin.assert:
        that:
          - '"0.0.0.0:443" in _ss_output.stdout'
        fail_msg: NGINX not listening on port 443.
        success_msg: NGINX listening on port 443.
