---

- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Check if NGINX is installed
      become: true
      check_mode: true
      ansible.builtin.package:
        name:
          - nginx
        state: present
      register: _package

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _package.changed
        fail_msg: NGINX not installed
        success_msg: NGINX installed

    - name: Check if NGINX is enabled
      become: true
      check_mode: true
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
      register: _service_enabled

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _service_enabled.changed
        fail_msg: NGINX not enabled
        success_msg: NGINX enabled

    - name: Check if NGINX is running
      become: true
      check_mode: true
      ansible.builtin.systemd_service:
        name: nginx
        state: started
      register: _service_running

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _service_running.changed
        fail_msg: NGINX not running
        success_msg: NGINX running

    - name: Check ss output
      ansible.builtin.command: ss -tuln
      changed_when: false
      register: _ss_output

    - name: Assert
      ansible.builtin.assert:
        that:
          - '"0.0.0.0:80" in _ss_output.stdout'
          - '"0.0.0.0:443" in _ss_output.stdout'
        fail_msg: NGINX not listening on port 80 or 443
        success_msg: NGINX listening on port 80 and 443
