---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: oss_reverse_proxy
  description: This role installs and configures NGINX as a reverse proxy on Linux machines.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy
        - focal

dependencies:
  - role: trippsc2.nginx.oss
