---
- name: Check if auth_basic directive is set in location block
  when:
    - _location_block.auth_basic is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        auth_basic {{ _location_block.auth_basic }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_basic_directive

- name: Verify auth_basic directive is set in location block
  when:
    - _location_block.auth_basic is defined
  ansible.builtin.assert:
    that:
      - not _auth_basic_directive.changed
    fail_msg: auth_basic directive is not set in location block.
    success_msg: auth_basic directive is set in location block.

- name: Check if auth_basic_user_file directive is set in location block
  when:
    - _location_block.auth_basic_user_file is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        auth_basic_user_file {{ _location_block.auth_basic_user_file }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_basic_user_file_directive

- name: Verify auth_basic_user_file directive is set in location block
  when:
    - _location_block.auth_basic_user_file is defined
  ansible.builtin.assert:
    that:
      - not _auth_basic_user_file_directive.changed
    fail_msg: auth_basic_user_file directive is not set in location block.
    success_msg: auth_basic_user_file directive is set in location block.
