---
- name: Check if gunzip directive is set in location block
  when:
    - _location_block.gunzip is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        gunzip {{ _location_block.gunzip | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _gunzip_directive

- name: Verify gunzip directive is set in location block
  when:
    - _location_block.gunzip is defined
  ansible.builtin.assert:
    that:
      - not _gunzip_directive.changed
    fail_msg: gunzip directive is not set in location block.
    success_msg: gunzip directive is set in location block.

- name: Check if gunzip_buffers directive is set in location block
  when:
    - _location_block.gunzip_buffers is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        gunzip_buffers {{ _location_block.gunzip_buffers.number }} {{ _location_block.gunzip_buffers.size }};"
    owner: root
    group: root
    mode: '0640'
  register: _gunzip_buffers_directive

- name: Verify gunzip_buffers directive is set in location block
  when:
    - _location_block.gunzip_buffers is defined
  ansible.builtin.assert:
    that:
      - not _gunzip_buffers_directive.changed
    fail_msg: gunzip_buffers directive is not set in location block.
    success_msg: gunzip_buffers directive is set in location block.
