---
- name: Check if access_log directive is set in location block (off)
  when:
    - _location_block.access_log is defined
    - _location_block.access_log.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        access_log off;"
    owner: root
    group: root
    mode: '0640'
  register: _access_log_off_directive

- name: Verify access_log directive is set in location block (off)
  when:
    - _location_block.access_log is defined
    - _location_block.access_log.off | default(false)
  ansible.builtin.assert:
    that:
      - not _access_log_off_directive.changed
    fail_msg: access_log directive is not set in location block.
    success_msg: access_log directive is set in location block.

- name: Check if access_log directive is set in location block
  loop: "{{ _location_block.access_log.logs }}"
  when:
    - _location_block.access_log is defined
    - not _location_block.access_log.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: >-
      {{ '        ' }}access_log {{ item.path -}}
        {%- if item.format is defined -%}
        {{- ' ' + item.format | string -}}
        {{- ' buffer=' + item.buffer | string if item.buffer is defined -}}
        {%- if item.gzip is defined -%}
        {{- ' gzip' -}}
        {{- '=' + item.gzip.level | string if item.gzip.level is defined -}}
        {%- endif -%}
        {{- ' flush=' + item.flush | string if item.flush is defined -}}
        {{- ' if=' + item.if | string if item.if is defined -}}
        {%- endif %};
    owner: root
    group: root
    mode: '0640'
  register: _access_log_directive

- name: Verify access_log directive is set in location block
  loop: "{{ _access_log_directive.results }}"
  when:
    - _location_block.access_log is defined
    - not _location_block.access_log.off | default(false)
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: access_log directive is not set in location block.
    success_msg: access_log directive is set in location block.
  loop_control:
    label: "{{ item.item }}"

- name: Check if open_log_file_cache directive is set in location block (off)
  when:
    - _location_block.open_log_file_cache is defined
    - _location_block.open_log_file_cache.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        open_log_file_cache off;"
    owner: root
    group: root
    mode: '0640'
  register: _open_log_file_cache_off_directive

- name: Verify open_log_file_cache directive is set in location block (off)
  when:
    - _location_block.open_log_file_cache is defined
    - _location_block.open_log_file_cache.off | default(false)
  ansible.builtin.assert:
    that:
      - not _open_log_file_cache_off_directive.changed
    fail_msg: open_log_file_cache directive is not set in location block.
    success_msg: open_log_file_cache directive is set in location block.

- name: Check if open_log_file_cache directive is set in location block
  when:
    - _location_block.open_log_file_cache is defined
    - not _location_block.open_log_file_cache.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: >-
      {{ '        ' }}open_log_file_cache max={{ _location_block.open_log_file_cache.max -}}
        {{- ' inactive=' + _location_block.open_log_file_cache.inactive | string if _location_block.open_log_file_cache.inactive is defined -}}
        {{- ' min_uses=' + _location_block.open_log_file_cache.min_uses | string if _location_block.open_log_file_cache.min_uses is defined -}}
        {{- ' valid=' + _location_block.open_log_file_cache.valid | string if _location_block.open_log_file_cache.valid is defined }};
    owner: root
    group: root
    mode: '0640'
  register: _open_log_file_cache_directive

- name: Verify open_log_file_cache directive is set in location block
  when:
    - _location_block.open_log_file_cache is defined
    - not _location_block.open_log_file_cache.off | default(false)
  ansible.builtin.assert:
    that:
      - not _open_log_file_cache_directive.changed
    fail_msg: open_log_file_cache directive is not set in location block.
    success_msg: open_log_file_cache directive is set in location block.

- name: Check if error_log directive is set in location block
  when:
    - _location_block.error_log is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: >-
      {{ '        ' }}error_log {{ _location_block.error_log.file -}}
        {{- ' ' + _location_block.error_log.level | string if _location_block.error_log.level is defined }};
    owner: root
    group: root
    mode: '0640'
  register: _error_log_directive

- name: Verify error_log directive is set in location block
  when:
    - _location_block.error_log is defined
  ansible.builtin.assert:
    that:
      - not _error_log_directive.changed
    fail_msg: error_log directive is not set in location block.
    success_msg: error_log directive is set in location block.
