---
- name: Check if stub_status directive is set in location block
  when:
    - _location_block.stub_status | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: >-
      {{ '    ' }}location {{ _location_block.modifier + ' ' if _location_block.modifier is defined -}}
        {{- _location_block.path }} {
    line: "        stub_status;"
    owner: root
    group: root
    mode: '0640'
  register: _stub_status_directive

- name: Verify stub_status directive is set in location block
  when:
    - _location_block.stub_status | default(false)
  ansible.builtin.assert:
    that:
      - not _stub_status_directive.changed
    fail_msg: stub_status directive is not set in location block.
    success_msg: stub_status directive is set in location block.
