---
_nginx_el_supported_versions:
  - '8'
  - '9'

_nginx_non_el_supported_distributions:
  - Debian
  - Ubuntu

_nginx_configure_selinux: >-
  {{ nginx_configure_selinux | default(_nginx_default_configure_selinux) }}

_nginx_user: "{{ nginx_user | default(_nginx_default_user) }}"
_nginx_group: "{{ nginx_group | default(_nginx_default_group) }}"

_nginx_firewall_type: >-
  {{ nginx_firewall_type | default(_nginx_default_firewall_type) }}
