---
_nginx_el_supported_versions:
  - '8'
  - '9'

_nginx_non_el_supported_distributions:
  - Debian
  - Ubuntu

_nginx_appstream_allowed_versions:
  '8':
    - '1.22'
    - '1.24'
  '9':
    - '1.20'
    - '1.22'
    - '1.24'
