---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 2048
    cpus: 2
    groups:
      - subjects
provisioner:
  name: ansible
  playbooks:
    converge: ../common/converge.yml
    verify: ../common/verify/main.yml
verifier:
  name: ansible

