---
- name: Validate string in map block
  ansible.builtin.assert:
    that:
      - _nginx_map_block.string | regex_search('^\$[a-zA-Z0-9_]+$')
    fail_msg: "Directive 'string' in 'map' in '{{ _nginx_http_config_file.destination }}' is not a valid variable name. Value: {{ _nginx_map_block.string }}"
    success_msg: "Directive 'string' in 'map' in '{{ _nginx_http_config_file.destination }}' is valid. Value: {{ _nginx_map_block.string }}"

- name: Validate variable in map block
  ansible.builtin.assert:
    that:
      - _nginx_map_block.variable | regex_search('^\$[a-zA-Z0-9_]+$')
    fail_msg: "Directive 'variable' in 'map' in '{{ _nginx_http_config_file.destination }}' is not a valid variable name. Value: {{ _nginx_map_block.variable }}"
    success_msg: "Directive 'variable' in 'map' in '{{ _nginx_http_config_file.destination }}' is valid. Value: {{ _nginx_map_block.variable }}"

- name: Validate content in map block is not empty
  ansible.builtin.assert:
    that:
      - _nginx_map_block.content | length > 0
    fail_msg: "Directive 'content' in 'map' in '{{ _nginx_http_config_file.destination }}' must not be empty list."
    success_msg: "Directive 'content' in 'map' in '{{ _nginx_http_config_file.destination }}' is not empty list."
