---
- name: Check if auth_jwt directive is set in HTTP config file (off)
  when:
    - _http_config_file.auth_jwt is defined
    - _http_config_file.auth_jwt.off | default(false) 
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: auth_jwt off;
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_off_directive

- name: Verify auth_jwt directive is set in HTTP config file (off)
  when:
    - _http_config_file.auth_jwt is defined
    - _http_config_file.auth_jwt.off | default(false)
  ansible.builtin.assert:
    that:
      - not _auth_jwt_off_directive.changed
    fail_msg: auth_jwt directive is not set in HTTP config file.
    success_msg: auth_jwt directive is set in HTTP config file.

- name: Check if auth_jwt directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt is defined
    - not _http_config_file.auth_jwt.off | default(false) 
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: >-
      auth_jwt {{ _http_config_file.auth_jwt.realm -}}
        {{- ' token=' + _http_config_file.auth_jwt.token | string if _http_config_file.auth_jwt.token is defined }};
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_directive

- name: Verify auth_jwt directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt is defined
    - not _http_config_file.auth_jwt.off | default(false)
  ansible.builtin.assert:
    that:
      - not _auth_jwt_directive.changed
    fail_msg: auth_jwt directive is not set in HTTP config file.
    success_msg: auth_jwt directive is set in HTTP config file.

- name: Check if auth_jwt_key_file directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_key_file is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "auth_jwt_key_file {{ _http_config_file.auth_jwt_key_file }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_key_file_directive

- name: Verify auth_jwt_key_file directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_key_file is defined
  ansible.builtin.assert:
    that:
      - not _auth_jwt_key_file_directive.changed
    fail_msg: auth_jwt_key_file directive is not set in HTTP config file.
    success_msg: auth_jwt_key_file directive is set in HTTP config file.

- name: Check if auth_jwt_key_request directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_key_request is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "auth_jwt_key_request {{ _http_config_file.auth_jwt_key_request }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_key_request_directive

- name: Verify auth_jwt_key_request directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_key_request is defined
  ansible.builtin.assert:
    that:
      - not _auth_jwt_key_request_directive.changed
    fail_msg: auth_jwt_key_request directive is not set in HTTP config file.
    success_msg: auth_jwt_key_request directive is set in HTTP config file.

- name: Check if auth_jwt_type directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_type is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "auth_jwt_key_request {{ _http_config_file.auth_jwt_type }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_type_directive

- name: Verify auth_jwt_type directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_type is defined
  ansible.builtin.assert:
    that:
      - not _auth_jwt_type_directive.changed
    fail_msg: auth_jwt_type directive is not set in HTTP config file.
    success_msg: auth_jwt_type directive is set in HTTP config file.

- name: Check if auth_jwt_require directive is set in HTTP config file
  loop: "{{ _http_config_file.auth_jwt_require | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: >-
      auth_jwt_require {{ item.values | join(' ') -}}
        {{- ' error=' + item.error | string if item.error is defined }};
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_require_directive

- name: Verify auth_jwt_require directive is set in HTTP config file
  loop: "{{ _auth_jwt_require_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: auth_jwt_require directive is not set in HTTP config file.
    success_msg: auth_jwt_require directive is set in HTTP config file.
  loop_control:
    label: "{{ item.item }}"

- name: Check if auth_jwt_key_cache directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_key_cache is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "auth_jwt_key_cache {{ _http_config_file.auth_jwt_key_cache }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_key_cache_directive

- name: Verify auth_jwt_key_cache directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_key_cache is defined
  ansible.builtin.assert:
    that:
      - not _auth_jwt_key_cache_directive.changed
    fail_msg: auth_jwt_key_cache directive is not set in HTTP config file.
    success_msg: auth_jwt_key_cache directive is set in HTTP config file.

- name: Check if auth_jwt_leeway directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_leeway is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "auth_jwt_leeway {{ _http_config_file.auth_jwt_leeway }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_leeway_directive

- name: Verify auth_jwt_leeway directive is set in HTTP config file
  when:
    - _http_config_file.auth_jwt_leeway is defined
  ansible.builtin.assert:
    that:
      - not _auth_jwt_leeway_directive.changed
    fail_msg: auth_jwt_leeway directive is not set in HTTP config file.
    success_msg: auth_jwt_leeway directive is set in HTTP config file.

- name: Check if auth_jwt_claim_set directive is set in HTTP config file
  loop: "{{ _http_config_file.auth_jwt_claim_set | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "auth_jwt_claim_set {{ item.variable }} {{ item.claims | join(' ') }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_claim_set_directive

- name: Verify auth_jwt_claim_set directive is set in HTTP config file
  loop: "{{ _auth_jwt_claim_set_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: auth_jwt_claim_set directive is not set in HTTP config file.
    success_msg: auth_jwt_claim_set directive is set in HTTP config file.
  loop_control:
    label: "{{ item.item }}"

- name: Check if auth_jwt_header_set directive is set in HTTP config file
  loop: "{{ _http_config_file.auth_jwt_header_set | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "auth_jwt_header_set {{ item.variable }} {{ item.claims | join(' ') }};"
    owner: root
    group: root
    mode: '0640'
  register: _auth_jwt_header_set_directive

- name: Verify auth_jwt_header_set directive is set in HTTP config file
  loop: "{{ _auth_jwt_header_set_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: auth_jwt_header_set directive is not set in HTTP config file.
    success_msg: auth_jwt_header_set directive is set in HTTP config file.
  loop_control:
    label: "{{ item.item }}"
