---
- name: Check if add_header directive is set in HTTP config file
  loop: "{{ _http_config_file.add_header | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "add_header {{ item.field }} {{ item.value }}{{ ' always' if item.always | default(false) }};"
    owner: root
    group: root
    mode: '0640'
  register: _add_header_directive

- name: Verify add_header directive is set in HTTP config file
  loop: "{{ _add_header_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: add_header directive is not set in HTTP config file.
    success_msg: add_header directive is set in HTTP config file.
  loop_control:
    label: "{{ item.item }}"

- name: Check if add_trailer directive is set in HTTP config file
  loop: "{{ _http_config_file.add_trailer | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "add_trailer {{ item.field }} {{ item.value }}{{ ' always' if item.always | default(false) }};"
    owner: root
    group: root
    mode: '0640'
  register: _add_trailer_directive

- name: Verify add_trailer directive is set in HTTP config file
  loop: "{{ _add_header_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: add_trailer directive is not set in HTTP config file.
    success_msg: add_trailer directive is set in HTTP config file.
  loop_control:
    label: "{{ item.item }}"

- name: Check if expires directive is set in HTTP config file (off)
  when:
    - _http_config_file.expires is defined
    - _http_config_file.expires.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: expires off;
    owner: root
    group: root
    mode: '0640'
  register: _expires_off_directive

- name: Verify expires directive is set in HTTP config file (off)
  when:
    - _http_config_file.expires is defined
    - _http_config_file.expires.off | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_off_directive.changed
    fail_msg: expires directive is not set in HTTP config file.
    success_msg: expires directive is set in HTTP config file.

- name: Check if expires directive is set in HTTP config file (max)
  when:
    - _http_config_file.expires is defined
    - not _http_config_file.expires.off | default(false)
    - _http_config_file.expires.max | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: expires max;
    owner: root
    group: root
    mode: '0640'
  register: _expires_max_directive

- name: Verify expires directive is set in HTTP config file (max)
  when:
    - _http_config_file.expires is defined
    - not _http_config_file.expires.off | default(false)
    - _http_config_file.expires.max | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_max_directive.changed
    fail_msg: expires directive is not set in HTTP config file.
    success_msg: expires directive is set in HTTP config file.

- name: Check if expires directive is set in HTTP config file (epoch)
  when:
    - _http_config_file.expires is defined
    - not _http_config_file.expires.off | default(false)
    - not _http_config_file.expires.max | default(false)
    - _http_config_file.expires.epoch | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: expires epoch;
    owner: root
    group: root
    mode: '0640'
  register: _expires_epoch_directive

- name: Verify expires directive is set in HTTP config file (epoch)
  when:
    - _http_config_file.expires is defined
    - not _http_config_file.expires.off | default(false)
    - not _http_config_file.expires.max | default(false)
    - _http_config_file.expires.epoch | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_epoch_directive.changed
    fail_msg: expires directive is not set in HTTP config file.
    success_msg: expires directive is set in HTTP config file.

- name: Check if expires directive is set in HTTP config file
  when:
    - _http_config_file.expires is defined
    - not _http_config_file.expires.off | default(false)
    - not _http_config_file.expires.max | default(false)
    - not _http_config_file.expires.epoch | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: >-
      expires {{ 'modified ' if _http_config_file.expires.modified | default(false) -}}
        {{- _http_config_file.expires.time }};
    owner: root
    group: root
    mode: '0640'
  register: _expires_directive

- name: Verify expires directive is set in HTTP config file
  when:
    - _http_config_file.expires is defined
    - not _http_config_file.expires.off | default(false)
    - not _http_config_file.expires.max | default(false)
    - not _http_config_file.expires.epoch | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_directive.changed
    fail_msg: expires directive is not set in HTTP config file.
    success_msg: expires directive is set in HTTP config file.
