---
- name: Check if mirror directive is set in HTTP config file (off)
  when:
    - _http_config_file.mirror is defined
    - _http_config_file.mirror.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: mirror off;
    owner: root
    group: root
    mode: '0640'
  register: _mirror_off_directive

- name: Verify mirror directive is set in HTTP config file (off)
  when:
    - _http_config_file.mirror is defined
    - _http_config_file.mirror.off | default(false)
  ansible.builtin.assert:
    that:
      - not _mirror_off_directive.changed
    fail_msg: mirror directive is not set in HTTP config file.
    success_msg: mirror directive is set in HTTP config file.

- name: Check if mirror directive is set in HTTP config file
  loop: "{{ _http_config_file.mirror.uris | default([]) }}"
  when:
    - _http_config_file.mirror is defined
    - not _http_config_file.mirror.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "mirror {{ item }};"
    owner: root
    group: root
    mode: '0640'
  register: _mirror_directive

- name: Verify mirror directive is set in HTTP config file
  loop: "{{ _mirror_directive.results }}"
  when:
    - _http_config_file.mirror is defined
    - not _http_config_file.mirror.off | default(false)
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: mirror directive is not set in HTTP config file.
    success_msg: mirror directive is set in HTTP config file.
  loop_control:
    label: "{{ item.item }}"

- name: Check if mirror_request_body directive is set in HTTP config file
  when:
    - _http_config_file.mirror_request_body is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "mirror_request_body {{ _http_config_file.mirror_request_body | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _mirror_request_body_directive

- name: Verify mirror_request_body directive is set in HTTP config file
  when:
    - _http_config_file.mirror_request_body is defined
  ansible.builtin.assert:
    that:
      - not _mirror_request_body_directive.changed
    fail_msg: mirror_request_body directive is not set in HTTP config file.
    success_msg: mirror_request_body directive is set in HTTP config file.
