---
- name: Check if rewrite_log directive is set in HTTP config file
  when:
    - _http_config_file.rewrite_log is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "rewrite_log {{ _http_config_file.rewrite_log | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _rewrite_log_directive

- name: Verify rewrite_log directive is set in HTTP config file
  when:
    - _http_config_file.rewrite_log is defined
  ansible.builtin.assert:
    that:
      - not _rewrite_log_directive.changed
    fail_msg: rewrite_log directive is not set in HTTP config file.
    success_msg: rewrite_log directive is set in HTTP config file.

- name: Check if uninitialized_variable_warn directive is set in HTTP config file
  when:
    - _http_config_file.uninitialized_variable_warn is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    line: "uninitialized_variable_warn {{ _http_config_file.uninitialized_variable_warn | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _uninitialized_variable_warn_directive

- name: Verify uninitialized_variable_warn directive is set in HTTP config file
  when:
    - _http_config_file.uninitialized_variable_warn is defined
  ansible.builtin.assert:
    that:
      - not _uninitialized_variable_warn_directive.changed
    fail_msg: uninitialized_variable_warn directive is not set in HTTP config file.
    success_msg: uninitialized_variable_warn directive is set in HTTP config file.
