---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: oss
  description: This role installs and configures NGINX OSS

  license: MIT

  min_ansible_version: '2.14'

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

collections:
  - ansible.posix
  - community.general

dependencies: []
