---
- name: Check if error_page directive is set in location if block
  loop: "{{ _location_block.error_page | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: >-
      {{ '            ' }}error_page {{ item.codes | join(' ') -}}
        {{- ' ' + item.response if item.response is defined -}}
        {{- ' ' + item.uri }};
    owner: root
    group: root
    mode: '0640'
  register: _error_page_directive

- name: Verify error_page directive is set in location if block
  loop: "{{ _error_page_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: error_page directive is not set in location if block.
    success_msg: error_page directive is set in location if block.
  loop_control:
    label: "{{ item.item }}"

- name: Check if limit_rate directive is set in location if block
  when:
    - _location_if_block.limit_rate is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            limit_rate {{ _location_if_block.limit_rate }};"
    owner: root
    group: root
    mode: '0640'
  register: _limit_rate_directive

- name: Verify limit_rate directive is set in location if block
  when:
    - _location_if_block.limit_rate is defined
  ansible.builtin.assert:
    that:
      - not _limit_rate_directive.changed
    fail_msg: limit_rate directive is not set in location if block.
    success_msg: limit_rate directive is set in location if block.

- name: Check if root directive is set in location if block
  when:
    - _location_if_block.root is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            root {{ _location_if_block.root }};"
    owner: root
    group: root
    mode: '0640'
  register: _root_directive

- name: Verify root directive is set in location if block
  when:
    - _location_if_block.root is defined
  ansible.builtin.assert:
    that:
      - not _root_directive.changed
    fail_msg: root directive is not set in location if block.
    success_msg: root directive is set in location if block.

- name: Check if sendfile directive is set in location if block
  when:
    - _location_if_block.sendfile is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            sendfile {{ _location_if_block.sendfile | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _sendfile_directive

- name: Verify sendfile directive is set in location if block
  when:
    - _location_if_block.sendfile is defined
  ansible.builtin.assert:
    that:
      - not _sendfile_directive.changed
    fail_msg: sendfile directive is not set in location if block.
    success_msg: sendfile directive is set in location if block.
