---
- name: Check if grpc_pass directive is set in location if block
  when:
    - _location_if_block.grpc_pass is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            grpc_pass {{ _location_if_block.grpc_pass }};"
    owner: root
    group: root
    mode: '0640'
  register: _grpc_pass_directive

- name: Verify grpc_pass directive is set in location if block
  when:
    - _location_if_block.grpc_pass is defined
  ansible.builtin.assert:
    that:
      - not _grpc_pass_directive.changed
    fail_msg: grpc_pass directive is not set in location if block.
    success_msg: grpc_pass directive is set in location if block.
