---
- name: Check if gzip directive is set in location if block
  when:
    - _location_if_block.gzip is defined
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            gzip {{ _location_if_block.gzip | ternary('on', 'off') }};"
    owner: root
    group: root
    mode: '0640'
  register: _gzip_directive

- name: Verify gzip directive is set in location if block
  when:
    - _location_if_block.gzip is defined
  ansible.builtin.assert:
    that:
      - not _gzip_directive.changed
    fail_msg: gzip directive is not set in location if block.
    success_msg: gzip directive is set in location if block.
