---
- name: Check if add_header directive is set in location if block
  loop: "{{ _location_if_block.add_header | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: >-
      {{ '            ' }}add_header {{ item.field }} {{ item.value -}}
        {{- ' always' if item.always | default(false) }};
    owner: root
    group: root
    mode: '0640'
  register: _add_header_directive

- name: Verify add_header directive is set in location if block
  loop: "{{ _add_header_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: add_header directive is not set in location if block.
    success_msg: add_header directive is set in location if block.
  loop_control:
    label: "{{ item.item }}"

- name: Check if add_trailer directive is set in location if block
  loop: "{{ _location_if_block.add_trailer | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: >-
      {{ '            ' }}add_trailer {{ item.field }} {{ item.value -}}
        {{- ' always' if item.always | default(false) }};
    owner: root
    group: root
    mode: '0640'
  register: _add_trailer_directive

- name: Verify add_trailer directive is set in location if block
  loop: "{{ _add_header_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: add_trailer directive is not set in location if block.
    success_msg: add_trailer directive is set in location if block.
  loop_control:
    label: "{{ item.item }}"

- name: Check if expires directive is set in location if block (off)
  when:
    - _location_if_block.expires is defined
    - _location_if_block.expires.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            expires off;"
    owner: root
    group: root
    mode: '0640'
  register: _expires_off_directive

- name: Verify expires directive is set in location if block (off)
  when:
    - _location_if_block.expires is defined
    - _location_if_block.expires.off | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_off_directive.changed
    fail_msg: expires directive is not set in location if block.
    success_msg: expires directive is set in location if block.

- name: Check if expires directive is set in location if block (max)
  when:
    - _location_if_block.expires is defined
    - not _location_if_block.expires.off | default(false)
    - _location_if_block.expires.max | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            expires max;"
    owner: root
    group: root
    mode: '0640'
  register: _expires_max_directive

- name: Verify expires directive is set in location if block (max)
  when:
    - _location_if_block.expires is defined
    - not _location_if_block.expires.off | default(false)
    - _location_if_block.expires.max | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_max_directive.changed
    fail_msg: expires directive is not set in location if block.
    success_msg: expires directive is set in location if block.

- name: Check if expires directive is set in location if block (epoch)
  when:
    - _location_if_block.expires is defined
    - not _location_if_block.expires.off | default(false)
    - not _location_if_block.expires.max | default(false)
    - _location_if_block.expires.epoch | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            expires epoch;"
    owner: root
    group: root
    mode: '0640'
  register: _expires_epoch_directive

- name: Verify expires directive is set in location if block (epoch)
  when:
    - _location_if_block.expires is defined
    - not _location_if_block.expires.off | default(false)
    - not _location_if_block.expires.max | default(false)
    - _location_if_block.expires.epoch | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_epoch_directive.changed
    fail_msg: expires directive is not set in location if block.
    success_msg: expires directive is set in location if block.

- name: Check if expires directive is set in location if block
  when:
    - _location_if_block.expires is defined
    - not _location_if_block.expires.off | default(false)
    - not _location_if_block.expires.max | default(false)
    - not _location_if_block.expires.epoch | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: >-
      {{ '            ' }}expires {{ 'modified ' if _location_if_block.expires.modified | default(false) -}}
        {{- _location_if_block.expires.time }};
    owner: root
    group: root
    mode: '0640'
  register: _expires_directive

- name: Verify expires directive is set in location if block
  when:
    - _location_if_block.expires is defined
    - not _location_if_block.expires.off | default(false)
    - not _location_if_block.expires.max | default(false)
    - not _location_if_block.expires.epoch | default(false)
  ansible.builtin.assert:
    that:
      - not _expires_directive.changed
    fail_msg: expires directive is not set in location if block.
    success_msg: expires directive is set in location if block.
