---
- name: Check if access_log directive is set in location if block (off)
  when:
    - _location_if_block.access_log is defined
    - _location_if_block.access_log.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            access_log off;"
    owner: root
    group: root
    mode: '0640'
  register: _access_log_off_directive

- name: Verify access_log directive is set in location if block (off)
  when:
    - _location_if_block.access_log is defined
    - _location_if_block.access_log.off | default(false)
  ansible.builtin.assert:
    that:
      - not _access_log_off_directive.changed
    fail_msg: access_log directive is not set in location if block.
    success_msg: access_log directive is set in location if block.

- name: Check if access_log directive is set in location if block
  loop: "{{ _location_if_block.access_log.logs }}"
  when:
    - _location_if_block.access_log is defined
    - not _location_if_block.access_log.off | default(false)
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: >-
      {{ '            ' }}access_log {{ item.path -}}
        {%- if item.format is defined -%}
        {{- ' ' + item.format | string -}}
        {{- ' buffer=' + item.buffer | string if item.buffer is defined -}}
        {%- if item.gzip is defined -%}
        {{- ' gzip' -}}
        {{- '=' + item.gzip.level | string if item.gzip.level is defined -}}
        {%- endif -%}
        {{- ' flush=' + item.flush | string if item.flush is defined -}}
        {{- ' if=' + item.if | string if item.if is defined -}}
        {%- endif %};
    owner: root
    group: root
    mode: '0640'
  register: _access_log_directive

- name: Verify access_log directive is set in location if block
  loop: "{{ _access_log_directive.results }}"
  when:
    - _location_if_block.access_log is defined
    - not _location_if_block.access_log.off | default(false)
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: access_log directive is not set in location if block.
    success_msg: access_log directive is set in location if block.
  loop_control:
    label: "{{ item.item }}"
