---
- name: Verify ngx_http_core_module directives
  ansible.builtin.include_tasks: http/server/location/if/core.yml

- name: Verify ngx_http_proxy_module directives
  ansible.builtin.include_tasks: http/server/location/if/proxy.yml

- name: Verify ngx_http_grpc_module directives
  ansible.builtin.include_tasks: http/server/location/if/grpc.yml

- name: Verify ngx_http_gzip_module directives
  ansible.builtin.include_tasks: http/server/location/if/gzip.yml

- name: Verify ngx_http_headers_module directives
  ansible.builtin.include_tasks: http/server/location/if/headers.yml

- name: Verify ngx_http_log_module directives
  ansible.builtin.include_tasks: http/server/location/if/log.yml

- name: Verify ngx_http_rewrite_module directives
  ansible.builtin.include_tasks: http/server/location/if/rewrite.yml

- name: Check if custom directive is set in location if block
  loop: "{{ _location_if_block.custom_directives | default([]) }}"
  become: true
  check_mode: true
  ansible.builtin.lineinfile:
    path: "{{ _http_config_file.destination }}"
    insertafter: "        if ({{ _location_if_block.condition }}) {"
    line: "            {{ item }}"
    owner: root
    group: root
    mode: '0640'
  register: _custom_directive

- name: Verify custom directive is set in location if block
  loop: "{{ _custom_directive.results }}"
  ansible.builtin.assert:
    that:
      - not item.changed
    fail_msg: "Custom directive '{{ item.item }}' is not set in location if block."
    success_msg: "Custom directive '{{ item.item }}' is set in location if block."
